### ISSUE TITLE
all Ports exposed?

### ISSUE THREAD

**Issue by hwinkel** [infinityworksltd/Guide_Rancher_Monitoring#5] opened 2016-04-14 23:40 UTC
Is it really required that the Rancher Template all service ports exposes?

**Comment by Rucknar** [comment] 2016-04-15 07:28
Not for a single environment deployment no. Those port declarations could be removed, it might affect how we do cross environment monitoring though. WIll look at that as we look at how best to cover cross environment support first.

**Comment by Rucknar** [comment] 2016-07-12 07:42
@hwinkel We've managed to remove a few of the exposed ports but the majority are generally available by design to enable cross env monitoring as mentioned above. Ideally I would have this as a toggle option, but i don't think the catalog format allows for such manipulation of the compose files just yet. I'm going to close this for now, if you feel it still needs to be open then let me know and i'll re-open.

**Closed by Rucknar** 2016-07-12 07:42 UTC
